#pragma config(Sensor, in1,    mobilePot,      sensorPotentiometer)
#pragma config(Sensor, in2,    liftRightPot,   sensorPotentiometer)
#pragma config(Sensor, in3,    armPot,         sensorPotentiometer)
#pragma config(Sensor, in4,    liftLeftPot,    sensorPotentiometer)
#pragma config(Sensor, in5,    driveGyro,      sensorGyro)
#pragma config(Sensor, dgtl1,  rightDriveEnc,  sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftDriveEnc,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  rollerEnc,      sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  MOSI,           sensorDigitalOut)
#pragma config(Sensor, dgtl8,  SCLK,           sensorDigitalOut)
#pragma config(Motor,  port1,           mobileGoal,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           driveBL,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           driveBR,       tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, None)
#pragma config(Motor,  port4,           driveFL,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           driveFR,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           swingingArm,   tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           roller,        tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           liftL,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           liftR,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Declare VEX as the robot platform

#pragma platform(VEX)

// Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

// **** Important programmer notes ****
//
// When upgrading ROBOTC the Robot Platform Settings are lost and must be reset
// otherwise compiler error will result. Ensure the following are set:
// 		Robot -> Platform Type -> VEX 2.0 Cortex
// 		Robot -> Platform Type -> VEX Robotics -> VEX 2.0 Cortex
// 		Robot -> Platform Type -> Natural Language (PLTW)
//
//
// Note: Sometime when upgrading FW on the controller and/or joystick, the FW for the
//       VEXNet Keys must also be upgraded. The symptom of needing this upgrade is a
//       failure of the controller and joystick to communicate with each other.
//
//
// Note: When RobotC refuses to download code to the robot, first try manually selecting the
//       COM port. If that doesn't work then it may be necessary reload the firmware. First
//       update the main FW and then the RobotC FW. Don't forget to rename robot afterwards.
//
//
// Variable info:
//
//		int, short, word - 2 bytes
//		long - 4 bytes
//		SensorValue() returns 2 byte value

// Control debugger windows by defining these pragmas
#pragma DebuggerWindows("debugStream")

#include "Team8800Lib.c"		// Utility routines to simplify programming
#include "Team8800Led.c"		// Routines to control the LED strip
#include "MultiTask.c"  // Motor slew control

// Delcarations

int number = 10;

// Initialize
void initialize();
void initializeGyro();
void selectTeamAlliance();

// Controller Input
//void processController();

// Autonomous
//void autonomousRoutines();

// Robot Action

//Functions
void moveLiftDown(int speed, int distance);
void moveArmOut();
void moveArmIn();
void moveArmOutAuto();
void moveArm(bool forward);
void moveLiftUp(int speed, int distance);
void moveLiftUpAuto(int speed, int distance);
void rollerIntake(int speed);
void rollerOutake(int speed, int time);

void autoLiftPIDControl (int position);
void liftPIDCalculate (int position);
void liftPIDControl(int position);
void checkLiftPos (int height);
void autoDrivePIDCalculate (int distance, bool time);
void autoDrivePIDControl (int distance, bool time);
void autoGyroPIDCalculate (int setAngle);
void autoGyroPIDControl (int setAngle);
void autoDriveGyroPIDCalculate (int setAngle, int distance);
void autoDriveGyroPIDControl (int setAngle, int distance);

//Auto Functions
void moveMobileGoalOutAndDrive(int speed, int distance);
void moveMobileGoalInAndDrive(int speed, int distance);
void autoLiftControl (int height);
void drive(int left, int right);
void driveForward(int speed, int distance);
void driveBackward(int speed, int distance);
void turnLeft(int speed, int distance);
void turnRight(int speed, int distance);
void clearDriveEnc();
void moveMobileGoalOutAuto();
void moveMobileGoalInAuto();
void moveMobileGoalOut();
void moveMobileGoalIn();
void moveMobileGoalInDistance(int distance);
void rollerOutakeAuto(int speed, int distance);
void collectMobileGoal();
void intakeMobileGoalAlignLoader();
void intakeMobileGoalAndStackFirstCone();
void stackSecondConeAndCollectThirdCone();
void stackThirdConeAndCollectFourthCone();
void autoDriveBackward();
void autoAlignWithZones();
void scoreMobileGoalInZones();
void autoAutoStackControl (int maxConeNum);
void autoLoader();
void scoreConeOnStationaryGoal();
void stationaryBlock();
void skillsFirstMobileGoal();
void skillsSecondMobileGoal();
void skillsThirdMobileGoal();

void autoStackStep(int liftPos);

void autoStack (int level);
void autoAutoStack(int level);
void postStacking();
void autoPostStacking();
void loaderPlacement();

// Constants and global vars
const byte MIN_JOYSTICK_THRESHOLD = 30;

const byte RED_ALLIANCE = 1;
const byte BLUE_ALLIANCE = 2;
byte allianceColor = BLUE_ALLIANCE;

const byte LEFT = 1;
const byte RIGHT = 2;
byte allianceSide = RIGHT;

const byte AUTONOMOUS_MODE_MOBILE_GOAL_5 = 1;
const byte AUTONOMOUS_MODE_MOBILE_GOAL_10 = 2;
const byte AUTONOMOUS_MODE_MOBILE_GOAL_20 = 3;
const byte AUTONOMOUS_MODE_STATIONARY = 4;
const byte AUTONOMOUS_MODE_BLOCK = 5;
const byte AUTONOMOUS_MODE_SKILLS = 6;
byte autonomousMode = AUTONOMOUS_MODE_MOBILE_GOAL_5;

const byte CONE_NUMBER_1 = 1;
const byte CONE_NUMBER_2 = 2;
const byte CONE_NUMBER_3 = 3;
const byte CONE_NUMBER_4 = 4;
const byte CONE_LOADER = 5;
const byte CONE_NUMBER_6 = 6;
const byte CONE_NUMBER_7 = 7;
const byte CONE_NUMBER_8 = 8;
byte autonomousConeNumber = CONE_NUMBER_1;

const byte PRESET_LEVEL_ONE = 1;
const byte PRESET_LEVEL_TWO = 2;
const byte PRESET_LEVEL_THREE = 3;
const byte PRESET_LEVEL_FOUR = 4;
const byte PRESET_LEVEL_FIVE = 5;
const byte PRESET_LEVEL_SIX = 6;
const byte PRESET_LEVEL_SEVEN = 7;
const byte PRESET_LEVEL_EIGHT = 8;
const byte PRESET_LEVEL_NINE = 9;
const byte PRESET_LEVEL_TEN = 10;
const byte PRESET_LEVEL_ELEVEN = 11;
const byte PRESET_LEVEL_TWELVE = 12;
const byte PRESET_LEVEL_THIRTEEN = 13;
const byte PRESET_LEVEL_FOURTEEN = 14;
const byte PRESET_LEVEL_FIFTEEN = 15;
byte presetLevel = PRESET_LEVEL_ONE;

unsigned long autonomousStartTime;

const byte AUTONOMOUS = 1;
const byte USER_CONTROL = 2;
byte robotMode = 1;

bool presetLevelActive = false;
bool presetLevelJustActive = false;

bool boingyPointOn = true;
bool armBack = false;
bool armFront = true;

bool stacking = false;
bool stackPrev = false;
bool justStacked = false;

bool increaseStackLvl;
bool increaseAutoStackLvl;

bool armIsBack = false;
bool armIsReallyBack;
bool armIsBackLvl1and2;
bool armIsForward;
bool liftLeftIsPosition4;
bool liftRightIsPosition4 = false;
bool liftIsPosition4Again = false;
bool liftIsPosition5;
bool liftIsPosition6;
bool liftIsDown = false;

bool liftLeftAtPosition;
bool liftRightAtPosition;
bool driveAtPosition;
bool turnAtPosition;

bool mobileGoalOut;

bool rollerIntaking = false;
bool outakeFinished = false;

bool btnSixUPressed = false;
bool btnSixDPressed = false;

bool presetLevelScrollUp = false;
bool presetLevelScrollDown = false;

bool timeUp = false;

bool mobileGoalIsOut;

int h1 = 480;
int h2 = 560;
int h3 = 680;
int h4 = 840;
int h5 = 1000;
int h6 = 1080;
int h7 = 1140;
int h8 = 1310;
int h9 = 1460;
int h10 = 1550;
int h11 = 1750;
int h12 = 1970;
int h13 = 2020;
int h14 = 2040;

int ah1 = 480;
int ah2 = 560;
int ah3 = 680;
int ah4 = 840;
int ah5 = 1000;
int ah6 = 1180;
int ah7 = 1140;
int ah8 = 1310;
int ah9 = 1460;
int ah10 = 1550;
int ah11 = 1750;
int ah12 = 1970;
int ah13 = 2020;
int ah14 = 2040;

int autoStackExraHeight = 100;
int autoStackOutTime = 450;
int autoStackDownTime = 300;

int armPower;

int stackLevel = 1;
int autoStacklvl = 4;
int prevStackLevel = 0;

int liftLeftPositionError = 65;
int liftRightPositionError = 65;
int drivePositionError = 1;
int turnPositionError = 1;
int turnDrivePositionError = 2;
int driveTurnPositionError = 200;
int armError = 2;

//Lift Auto Proportional
float autoLiftkp = 0.35;

//Lift PID values
float liftkp = 0.63;
float liftki = 0.04;
float liftkd = -0.05;

//Drive PID values
float drivekp = 0.25;
float driveki = 0.0036;
float drivekd = 0.06;

//Turn PID values
float turnkp = 0.7;
float turnki = 0.000004;
float turnkd = 0.04;

//Turn Drive PID values
float turnDrivekp;
float turnDriveki;
float turnDrivekd;

//Drive Turn PID values
float driveTurnkp = 0.75;
float driveTurnki;
float driveTurnkd;

float turnError;

int driveCurrent;
int gyroCurrent;
int overallCurrentLeft;
int overallCurrentRight;

int maxTurnPower = 15;

int rollerSpeed;

void pre_auton()
{
	bStopTasksBetweenModes = true;

	clearDebugStream();
	writeDebugStreamLine("Pre-Autonomous...");

	initializeGyro();

	// Select alliance using LCD and indicate selection with LEDs
	selectTeamAlliance();
}

task autonomousRoutines()
{
	switch (autonomousMode) {
	case AUTONOMOUS_MODE_MOBILE_GOAL_5:
		//////////////////////////////////////////////////////////////Mobile Goal 5////////////////////////

		if (allianceColor == BLUE_ALLIANCE) {
			theaterChaseTask(0, 0, 127, 50, 15000);
			} else {
			theaterChaseTask(127, 0, 0, 50, 15000);
		}

		motor[roller] = 40;

		clearTimer(T2);
		clearDriveEnc();

		collectMobileGoal();

		clearTimer(T2);
		clearDriveEnc();

		if (autonomousConeNumber == CONE_LOADER) {
			intakeMobileGoalAlignLoader();

			clearTimer(T2);
			clearDriveEnc();

			autoLoader();

			clearTimer(T2);
			clearDriveEnc();

			loaderPlacement();
		}

		///////////////////////////////////////////////////////////////////////End Mobile Goal 5//////////////////////////
		break;

	case AUTONOMOUS_MODE_MOBILE_GOAL_10:
		/////////////////////////////////////////////////////////////////////////////Mobile Goal 10///////////////////////////////////////////

		if (allianceColor == BLUE_ALLIANCE) {
			theaterChaseTask(0, 0, 127, 50, 15000);
			} else {
			theaterChaseTask(127, 0, 0, 50, 15000);
		}

		motor[roller] = 40;

		clearTimer(T2);
		clearDriveEnc();

		collectMobileGoal();

		clearTimer(T2);
		clearDriveEnc();

		if (autonomousConeNumber == CONE_LOADER) {
			intakeMobileGoalAlignLoader();

			clearTimer(T2);
			clearDriveEnc();

			autoLoader();

			clearTimer(T2);
			clearDriveEnc();

			loaderPlacement();

			drive(0, 0);
		}

		//////////////////////////////////////////////////////End of Mobile Goal 10/////////////////////////////////
		break;

	case AUTONOMOUS_MODE_MOBILE_GOAL_20:
		////////////////////////////////////////////////////////////////////////////////Mobile Goal 20/////////////////////////////
		if (autonomousConeNumber == CONE_NUMBER_1 || autonomousConeNumber == CONE_NUMBER_2 || autonomousConeNumber == CONE_NUMBER_3 || autonomousConeNumber == CONE_NUMBER_4) {
			motor[roller] = 40;

			clearDriveEnc();
			clearTimer(T2);

			collectMobileGoal();

		}
		if (autonomousConeNumber == CONE_NUMBER_2 || autonomousConeNumber == CONE_NUMBER_3 || autonomousConeNumber == CONE_NUMBER_4) {
			clearDriveEnc();
			clearTimer(T2);

			intakeMobileGoalAndStackFirstCone();

		}
		if (autonomousConeNumber == CONE_NUMBER_3 || autonomousConeNumber == CONE_NUMBER_4) {

			clearDriveEnc();
			clearTimer(T2);

			stackSecondConeAndCollectThirdCone();
		}
		if (autonomousConeNumber == CONE_NUMBER_4) {

			clearDriveEnc();
			clearTimer(T2);

			stackThirdConeAndCollectFourthCone();
		}

		clearDriveEnc();
		clearTimer(T2);

		autoAlignWithZones();

		clearDriveEnc();
		clearTimer(T2);

		scoreMobileGoalInZones();


		if (allianceColor == BLUE_ALLIANCE) {
			theaterChaseTask(0, 0, 127, 50, 15000);
			} else {
			theaterChaseTask(127, 0, 0, 50, 15000);
		}

		//////////////////////////////////////////////////////End of Mobile Goal 20/////////////////////////////////////////////////////
		break;

	case AUTONOMOUS_MODE_STATIONARY:
		//////////////////////////////////////////////////////////Stationary/////////////////////////////////////
		motor[roller] = 40;

		clearDriveEnc();
		clearTimer(T2);

		scoreConeOnStationaryGoal();

		clearDriveEnc();
		clearTimer(T2);

		stationaryBlock();

		if (allianceColor == BLUE_ALLIANCE) {
			theaterChaseTask(0, 0, 127, 50, 15000);
			} else {
			theaterChaseTask(127, 0, 0, 50, 15000);
		}

		///////////////////////////////////////////////////////////////End of Stationary///////////////////////////////////////////
		break;

	case AUTONOMOUS_MODE_BLOCK:
		/////////////////////////////////////////////////////////////Block/////////////////////////////////////////////////////



		if (allianceColor == BLUE_ALLIANCE) {
			theaterChaseTask(0, 0, 127, 50, 15000);
			} else {
			theaterChaseTask(127, 0, 0, 50, 15000);
		}

		/////////////////////////////////////////////////////////////End of Block/////////////////////////////////////////////////////
		break;

	case AUTONOMOUS_MODE_SKILLS:
		/////////////////////////////////////////////////////////////////////////////Skills////////////////////////////////

		clearDriveEnc();
		clearTimer(T2);

		skillsFirstMobileGoal();

		clearDriveEnc();
		clearTimer(T2);

		skillsSecondMobileGoal();

		clearDriveEnc();
		clearTimer(T2);

		skillsThirdMobileGoal();


		if (allianceColor == BLUE_ALLIANCE) {
			theaterChaseTask(0, 0, 127, 50, 15000);
			} else {
			theaterChaseTask(127, 0, 0, 50, 15000);
		}

		//////////////////////////////////////////////////////////End of Skills/////////////////////////////////////////////
		break;
	}
}

task autonomous()
{
	robotMode = AUTONOMOUS;

	autonomousStartTime = nSysTime;
	writeDebugStreamLine("Starting Autonomous...");

	initialize();

	if (false) AutonomousCodePlaceholderForTesting();  // complains if I remove this

	startTask(autonomousRoutines);
}

task ProcessController() {
	while(true) {

		/*
		Main Controller:
		joysticks = drive
		8U mobile goal full out
		8D mobile goal full in
		8L mobile goal partial in
		8R mobile goal partial out

		Partner Contorller:
		5U lift up
		5D lift down
		6D roller out
		6U roller in
		7U
		7D stop auto stacking and reset to level 1
		7L lift at mobile goal height
		7R
		8U acivate current level
		8D activate last level
		8L arm out
		8R arm in

		*/

		// --- Joysticks to control robot driving (main controller only)

		static byte rightJoystickY, leftJoystickY, prevRightJoystickY = 0, prevLeftJoystickY = 0;

		rightJoystickY = readRightJoystickYAxis();
		leftJoystickY = readLeftJoystickYAxis();

		static bool rightDriveMoving = false;
		if (abs(rightJoystickY) > MIN_JOYSTICK_THRESHOLD) {
			rightDriveMoving = true;
			motorReq2[driveFR] = rightJoystickY;
			motorReq2[driveBR] = rightJoystickY;
			writeDebugStreamLine("Right: %d%%", rightJoystickY);
			} else {
			rightDriveMoving = false;
			motorReq2[driveFR] = 0;
			motorReq2[driveBR] = 0;
		}

		static bool leftDriveMoving = false;
		if (abs(leftJoystickY) > MIN_JOYSTICK_THRESHOLD) {
			leftDriveMoving = true;
			motorReq2[driveFL] = leftJoystickY;
			motorReq2[driveBL] = leftJoystickY;
			writeDebugStreamLine("Left: %d%%", leftJoystickY);
			} else {
			leftDriveMoving = false;
			motorReq2[driveFL] = 0;
			motorReq2[driveBL] = 0;
		}

		if (!stacking) {
			if (isButtonPressed(Btn8RXmtr2)) {
				armIsBack = true;
				} else if (isButtonPressed(Btn8LXmtr2)) {
				armIsBack = false;
			}

			if (armIsBack) {
				moveArmOut();
				} else if (!armIsBack) {
				moveArmIn();
			}
		}

		//Mobile Goal control on joystick
		if (isButtonPressed(Btn8U)) {
			mobileGoalOut = true;
			} else if (isButtonPressed(Btn8D)) {
			mobileGoalOut = false;
		}

		if (isButtonPressed(Btn8R)) {
			moveMobileGoalOut();
			} else if (isButtonPressed(Btn8L)) {
			moveMobileGoalIn();
			} else if (mobileGoalOut) {
			moveMobileGoalOut();
			} else if (!mobileGoalOut) {
			moveMobileGoalIn();
		}

		//Roller control
		if (!stacking) {
			if (isButtonPressed(Btn6DXmtr2)) {
				motor[roller] = -127;
				} else if (isButtonPressed(Btn6UXmtr2)) {
				motor[roller] = 127;
				} else {
				motor[roller] = 25;
				//motor[roller] = 0;
			}
		}

		//Move lift
		if (!stacking) {
			if (isButtonPressed(Btn5UXmtr2)) {
				motor[liftL] = 127;
				motor[liftR] = 127;
				//liftPIDControl(1000);
				stacking = false;
				justStacked = false;
				stackPrev = false;
				} else if (isButtonPressed(Btn5DXmtr2)) {
				motor[liftL] = -90;
				motor[liftR] = -90;
				//liftPIDControl(500);
				stacking = false;
				justStacked = false;
				stackPrev = false;
				} else if (isButtonPressed(Btn7LXmtr2)) {
				autoLiftPIDControl(700);
				} else {
				motor[liftL] = 0;
				motor[liftR] = 0;
			}
		}

		//Activate curent level
		if (isButtonPressed(Btn8UXmtr2)) {
			stacking = true;
		}

		if (stacking) {
			autoStack(stackLevel);
			} else if (stackPrev) {
			autoStack(prevStackLevel);
			} else if (justStacked) {
			postStacking();
		}

		//Activate Stack
		/*if (isButtonPressed(Btn7RXmtr2)) {
		liftLeftAtPosition = true;
		liftRightAtPosition = true;
		}*/

		//Activate last level
		if (isButtonPressed(Btn8DXmtr2)) {
			stackPrev = true;
		}

		//Increase stack level
		if (isButtonPressed(Btn8UXmtr2) && increaseStackLvl) {
			prevStackLevel ++;
			stackLevel ++;
			increaseStackLvl = false;
		}

		//Deactivate stacking emergency
		if (isButtonPressed(Btn7UXmtr2)) {
			stacking = false;
			justStacked = false;
			stackPrev = false;
		}

		//Deactivate stacking reset to 1
		if (isButtonPressed(Btn7DXmtr2)) {
			stacking = false;
			justStacked = false;
			stackPrev = false;
			stackLevel = 0;
			prevStackLevel = -1;
		}

		//writeDebugStreamLine("stack level %d", stackLevel);
		//writeDebugStreamLine("Prev stack level, %d", prevStackLevel);
		//writeDebugStreamLine("mobile,                                                                           %d", SensorValue[mobilePot]);
		//writeDebugStreamLine("               roller Enc, %d", SensorValue[rollerEnc]);
		//writeDebugStreamLine("arm pot,                                                    %d", SensorValue[armPot]);
		//writeDebugStreamLine("arm power,                                                    %d", armPower );
		//writeDebugStreamLine("left pot, %d", SensorValue[liftLeftPot]);
		//writeDebugStreamLine("right pot,                    %d", SensorValue[liftRightPot]);
		//writeDebugStreamLine("Increase Stack level,                    %d", increaseStackLvl);


		writeDebugStreamLine("right drive enc                    %d", SensorValue[rightDriveEnc]);
		writeDebugStreamLine("left drive enc        %d", SensorValue[leftDriveEnc]);

		//writeDebugStreamLine("Gyro Values,      %d", SensorValue(driveGyro));
		//writeDebugStreamLine("Lift right pot,      %d", SensorValue(liftRightPot));
		//writeDebugStreamLine("						Lift Left pot,      %d", SensorValue(liftLeftPot));

		//datalogAddValueWithTimeStamp(6, SensorValue[liftLeftPot]);
		//datalogAddValueWithTimeStamp(5, SensorValue[liftRightPot]);
		datalogAddValueWithTimeStamp(6, SensorValue[armPot]);

		//datalogAddValueWithTimeStamp(0, SensorValue[liftLeftPot]);
		//datalogAddValueWithTimeStamp(1, SensorValue[liftRightPot]);

		if (isButtonClick(Btn7U)) {
			theaterChaseTask(127, 0, 127, 127, 15000);
		}

		if (isButtonClick(Btn7R)) {
			theaterChaseTask(0, 0, 127, 127, 15000);
		}

		if (isButtonClick(Btn7L)) {
			theaterChaseTask(127, 0, 0, 127, 15000);
		}

		if (isButtonClick(Btn7D)) {
			rainbowCycleTask(0, 15000);
		}

		// --- Choose alliance if both Left & Right LCD Buttons are pressed

		if ((nLCDButtons & (kButtonLeft | kButtonRight)) == (kButtonLeft | kButtonRight)) {
			selectTeamAlliance();
		}

		//writeDebugStreamLine("value Arm pot %d", SensorValue[armPot]);

		wait1Msec(15);
	}
}

task usercontrol()
{
	robotMode = USER_CONTROL;

	if (false) CodePlaceholderForTesting();	// complains if I remove this

	writeDebugStreamLine("Starting User Control...");
	writeDebugStreamLine("Main battery level: %3.2f", nAvgBatteryLevel * 0.001);
	writeDebugStreamLine("Backup battery level: %3.2f", BackupBatteryLevel * 0.001);

	initialize();

	startTask(MotorSlewRateTask);
	startTask(ProcessController);
}

void initialize()
{
	// Library routines thread
	startTask(activateLib);

	// LED strip routines thread
	setupLedStrip();

	//Clear Sensors
	SensorValue[rightDriveEnc] = 0;
	SensorValue[leftDriveEnc] = 0;
	SensorValue[rollerEnc] = 0;

	stacking = false;
	stackPrev = false;
	liftLeftAtPosition = false;
	liftRightAtPosition = false;
	armIsReallyBack = false;
	increaseStackLvl = false;
	justStacked = false;
	outakeFinished = false;

	datalogClear();

	presetLevel = PRESET_LEVEL_ONE;
}

void timerCallback(unsigned int timerId)
{

}

void selectTeamAlliance()
{
	// Defaults
	allianceColor = BLUE_ALLIANCE;
	allianceSide = RIGHT;
	autonomousMode = AUTONOMOUS_MODE_MOBILE_GOAL_20;
	//return;

	//SensorValue[ledGreen] = 0;
	//SensorValue[ledRed] = 0;

	// Zero out encoder positions

	// Clear LCD and turn on backlight
	clearLCDLine(0);
	clearLCDLine(1);
	bLCDBacklight = true;

	// Display alliance selection
	displayLCDString(0, 0, " Team Color  ");
	displayLCDString(1, 0, " Blue       Red ");

	bool allianceSelected = false;
	while (!allianceSelected) {	//bIfiRobotDisabled
		// Wait for button press
		switch (getLcdButtons()) {
		case kButtonLeft:
			allianceColor = BLUE_ALLIANCE;
			displayLCDString(1, 0, "[Blue]      Red ");
			allianceSelected = true;
			break;

		case kButtonRight:
			allianceColor = RED_ALLIANCE;
			displayLCDString(1, 0, "Blue       [Red]");
			allianceSelected = true;
			break;
		}

		wait1Msec(10);
	}

	// Display autonomous selection
	wait1Msec(500);

	// Display alliance selection
	displayLCDString(0, 0, " Team Side  ");
	displayLCDString(1, 0, " Left     Right ");

	bool sideSelected = false;
	while (!sideSelected) {	//bIfiRobotDisabled
		// Wait for button press
		switch (getLcdButtons()) {
		case kButtonLeft:
			allianceSide = LEFT;
			displayLCDString(1, 0, "[Left]    Right ");
			sideSelected = true;
			break;

		case kButtonRight:
			allianceSide = RIGHT;
			displayLCDString(1, 0, "Left     [Right]");
			sideSelected = true;
			break;
		}
		wait1Msec(10);
	}

	// Display autonomous selection
	wait1Msec(500);

	displayLCDString(0, 0, "Autonomous Type ");
	//displayLCDString(1, 0, "Full  Min  None ");

	bool autonomousTypeSelected = false;
	int scrollCountType = 1;
	byte scrolledAutoType = AUTONOMOUS_MODE_MOBILE_GOAL_5;
	while (!autonomousTypeSelected) {
		// Wait for button press
		if(nLCDButtons == 1) {
			scrollCountType -= 1;
		}
		if(nLCDButtons == 4) {
			scrollCountType += 1;
		}
		if(nLCDButtons == 2) {
			autonomousMode = scrolledAutoType;
			autonomousTypeSelected = true;
		}

		switch (scrollCountType) {
		case 1:
			scrolledAutoType = AUTONOMOUS_MODE_MOBILE_GOAL_5;
			displayLCDString(1, 0, "[5]10 20 ST B S ");
			wait1Msec(200);
			break;

		case 2:
			scrolledAutoType = AUTONOMOUS_MODE_MOBILE_GOAL_10;
			displayLCDString(1, 0, " 5[10]20 ST B S ");
			wait1Msec(200);
			break;

		case 3:
			scrolledAutoType = AUTONOMOUS_MODE_MOBILE_GOAL_20;
			displayLCDString(1, 0, " 5 10[20]ST B S ");
			wait1Msec(200);
			break;

		case 4:
			scrolledAutoType = AUTONOMOUS_MODE_STATIONARY;
			displayLCDString(1, 0, " 5 10 20[ST]B S ");
			wait1Msec(200);
			break;

		case 5:
			scrolledAutoType = AUTONOMOUS_MODE_BLOCK;
			displayLCDString(1, 0, " 5 10 20 ST[B]S ");
			wait1Msec(200);
			break;

		case 6:
			scrolledAutoType = AUTONOMOUS_MODE_SKILLS;
			displayLCDString(1, 0, " 5 10 20 ST B[S]");
			wait1Msec(200);
			break;
		}

		wait1Msec(10);
	}

	wait1Msec(500);

	// Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);

	displayLCDString(0, 0, "Cone Number ");
	//displayLCDString(1, 0, "Full  Min  None ");

	bool coneNumberSelected = false;
	int scrollCountNumber = 1;
	byte scrolledAutoNumber = CONE_NUMBER_1;
	while (!coneNumberSelected) {
		// Wait for button press
		if(nLCDButtons == 1) {
			scrollCountNumber -= 1;
		}
		if(nLCDButtons == 4) {
			scrollCountNumber += 1;
		}
		if(nLCDButtons == 2) {
			autonomousConeNumber = scrolledAutoNumber;
			coneNumberSelected = true;
		}

		switch (scrollCountNumber) {
		case 1:
			scrolledAutoNumber = CONE_NUMBER_1;
			displayLCDString(1, 0, "[1]2 3 4 L 6 7 8");
			wait1Msec(200);
			break;

		case 2:
			scrolledAutoNumber = CONE_NUMBER_2;
			displayLCDString(1, 0, " 1[2]3 4 L 6 7 8");
			wait1Msec(200);
			break;

		case 3:
			scrolledAutoNumber = CONE_NUMBER_3;
			displayLCDString(1, 0, " 1 2[3]4 L 6 7 8");
			wait1Msec(200);
			break;

		case 4:
			scrolledAutoNumber = CONE_NUMBER_4;
			displayLCDString(1, 0, " 1 2 3[4]L 6 7 8");
			wait1Msec(200);
			break;

		case 5:
			scrolledAutoNumber = CONE_LOADER;
			displayLCDString(1, 0, " 1 2 3 4[L]6 7 8");
			wait1Msec(200);
			break;

		case 6:
			scrolledAutoNumber = CONE_NUMBER_6;
			displayLCDString(1, 0, " 1 2 3 4 L[6]7 8");
			wait1Msec(200);
			break;

		case 7:
			scrolledAutoNumber = CONE_NUMBER_7;
			displayLCDString(1, 0, " 1 2 3 4 L 6[7]8");
			wait1Msec(200);
			break;

		case 8:
			scrolledAutoNumber = CONE_NUMBER_8;
			displayLCDString(1, 0, " 1 2 3 4 L 6 7[8");
			wait1Msec(200);
			break;
		}

		wait1Msec(10);
	}

	wait1Msec(500);

	// Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
}

void initializeGyro() {
	writeDebugStreamLine("Gyro before initialize %d", SensorValue[in8]);

	SensorType(driveGyro) = sensorNone;
	wait1Msec(1000);
	SensorType(driveGyro) = sensorGyro;
	wait1Msec(2000);

	writeDebugStreamLine("Gyro after initialize %d", SensorValue[in8]);
}

void moveArmOut () {
	if (SensorValue[armPot] < 2700) {
		motor[swingingArm] = 120;
		armPower = 120;
		} else if (SensorValue[armPot] >= 2700) {
		motor[swingingArm] = 0;
		armPower = 0;
		armIsReallyBack = false;
	}
}

void moveArmIn () {
	if (SensorValue[armPot] > 840) {
		motor[swingingArm] = -120;
		armPower = -120;
		writeDebugStreamLine("swinging arm pot %d", SensorValue[armPot]);
		} else if (SensorValue[armPot] <= 830) {
		motor[swingingArm] = 0;
		armPower = 0;
		armIsReallyBack = true;
	}
}

void moveArmOutAuto() {
	while(SensorValue[armPot] > 2000) {
		motor[swingingArm] = 100;
	}
	motor[swingingArm] = 0;
}

void moveArm (bool forward) {
	if (forward) {
		moveArmOut();
		} else {
		moveArmIn();
	}
}

void rollerIntake(int speed) {
	motor[roller] = speed;
	rollerSpeed = speed;
	//	writeDebugStreamLine("Set speed %d", rollerSpeed);
}

void rollerOutake(int speed, int time) {
	if (time1[T3] < time) {
		motor[roller] = speed;
		} else {
		motor [roller] = 0;
		outakeFinished = true;
	}
}

void rollerOutakeAuto(int speed, int distance) {
	while (distance > SensorValue[rollerEnc]) {
		motor[roller] = speed;
	}
	motor [roller] = 0;
}

//Drive function for auto
void drive(int left, int right) {
	turnMotor(driveFL, left);
	turnMotor(driveFR, right);
	turnMotor(driveBL, left);
	turnMotor(driveBR, right);
}
//Drive function with encoders for auto
void driveForward(int speed, int distance) {
	while (SensorValue[rightDriveEnc] < distance && SensorValue[leftDriveEnc] < distance) {
		writeDebugStreamLine(" Left Encoder: %d", SensorValue[leftDriveEnc]);
		writeDebugStreamLine(" Right Encoder: %d", SensorValue[rightDriveEnc]);
		writeDebugStreamLine("Moving forward");
		drive(speed, speed);
	}
	drive(0, 0);

	SensorValue[rightDriveEnc] = 0;
	SensorValue[leftDriveEnc] = 0;
	writeDebugStreamLine("Front Left Encoder: %d", SensorValue[leftDriveEnc]);
	writeDebugStreamLine("Front Right Encoder: %d", SensorValue[rightDriveEnc]);
}

void driveBackward(int speed, int distance) {
	while (SensorValue[rightDriveEnc] > distance && SensorValue[leftDriveEnc] > distance) {
		drive(speed, speed);
	}
	drive(0, 0);

	SensorValue[rightDriveEnc] = 0;
	SensorValue[leftDriveEnc] = 0;
}

void turnLeft(int speed, int distance) {
	while (SensorValue[leftDriveEnc] < distance && SensorValue[rightDriveEnc] > (-distance)) {
		drive(-speed, speed);
	}
	drive(0, 0);

	SensorValue[rightDriveEnc] = 0;
	SensorValue[leftDriveEnc] = 0;
}

void turnRight(int speed, int distance) {
	while (SensorValue[leftDriveEnc] > (-distance) && SensorValue[rightDriveEnc] < distance) {
		drive(speed, -speed);
	}
	drive(0, 0);

	SensorValue[rightDriveEnc] = 0;
	SensorValue[leftDriveEnc] = 0;
}

void clearDriveEnc() {
	SensorValue[rightDriveEnc] = 0;
	SensorValue[leftDriveEnc] = 0;
}

void  moveMobileGoalIn() {
	if (SensorValue[mobilePot] < 3100) {
		motor[mobileGoal] = 127;
		mobileGoalIsOut = true;
		} else {
		motor[mobileGoal] = 40;
		mobileGoalIsOut = false;
	}
}

void moveMobileGoalInAuto() {
	while (SensorValue[mobilePot] > 230) {
		motor[mobileGoal] = 127;
	}
	motor[mobileGoal] = 0;
}

void moveMobileGoalInDistance(int distance) {
	while (SensorValue[mobilePot] > distance) {
		motor[mobileGoal] = 127;
	}
	motor[mobileGoal] = 0;
}

void moveMobileGoalOut() {
	if (SensorValue[mobilePot] > 2000) {
		motor[mobileGoal] = -127;
		mobileGoalIsOut = false;
		} else {
		motor[mobileGoal] = -20;
		mobileGoalIsOut = true;
	}
}

void moveMobileGoalOutAuto() {
	while (SensorValue[mobilePot] < 2000) {
		motor[mobileGoal] = -127;
	}
	motor[mobileGoal] = 0;
}

void moveMobileGoalOutAndDrive(int speed, int distance) {
	while (SensorValue[rightDriveEnc] < distance && SensorValue[leftDriveEnc] < distance) {
		drive(speed, speed);
		while (SensorValue[mobilePot] < 2000) {
			motor[mobileGoal] = -127;
		}
		motor[mobileGoal] = 0;
	}
	drive(0, 0);

	SensorValue[rightDriveEnc] = 0;
	SensorValue[leftDriveEnc] = 0;
}

void moveMobileGoalInAndDrive(int speed, int distance) {
	while (SensorValue[rightDriveEnc] > distance && SensorValue[leftDriveEnc] > distance) {
		drive(speed, speed);
		while (SensorValue[mobilePot] > 180) {
			motor[mobileGoal] = 127;
		}
		motor[mobileGoal] = 0;
	}
	drive(0, 0);
}


void moveLiftUp(int speed, int distance) {
	if (((SensorValue[liftLeftPot] + SensorValue[liftRightPot])/2) < distance) {
		motor [liftL] = speed;
		motor [liftR] = speed;
		} else {
		motor [liftL] = 0;
		motor [liftR] = 0;
	}
}

void moveLiftUpAuto(int speed, int distance) {
	while (((SensorValue[liftLeftPot] + SensorValue[liftRightPot])/2) < distance) {
		motor [liftL] = speed;
		motor [liftR] = speed;
	}
	motor [liftL] = 0;
	motor [liftR] = 0;
}

void moveLiftDown(int speed, int distance) {
	if (((SensorValue[liftLeftPot] + SensorValue[liftRightPot])/2) > distance) {
		motor [liftL] = -speed;
		motor [liftR] = -speed;
		} else {
		motor [liftL] = 0;
		motor [liftR] = 0;
	}
}

void autoLiftPIDControl (int position) {
	float leftCurrent;
	float rightCurrent;

	float leftProportion;
	float rightProportion;

	float liftLeftError;
	float liftRightError;

	float leftPot = SensorValue[liftLeftPot];
	float rightPot = SensorValue[liftRightPot];

	//Find lift error
	liftLeftError = position - leftPot;
	liftRightError = position - rightPot;

	leftProportion = liftLeftError * autoLiftkp;
	rightProportion = liftRightError * autoLiftkp;

	leftCurrent = leftProportion;
	rightCurrent = rightProportion;

	if (leftCurrent > 127) {
		leftCurrent = 127;
	}
	if (rightCurrent > 127) {
		rightCurrent = 127;
	}
	if (leftCurrent < -127) {
		leftCurrent = -127;
	}
	if (rightCurrent < -127) {
		rightCurrent = -127;
	}

	motor[liftL] = leftCurrent;
	motor[liftR] = leftCurrent;

	//writeDebugStreamLine("left pot %d", leftPot);
	//writeDebugStreamLine("             right pot %d", rightPot);
	//writeDebugStreamLine("arm %d", armIsReallyBack);
	//writeDebugStreamLine("  left integral %d", sharedIntegral);
	//writeDebugStreamLine("                          right integral %d", rightIntegral);
	//writeDebugStreamLine("position %d", position);
	//writeDebugStreamLine("          left error %d", liftLeftError);
	//writeDebugStreamLine("                  right error %d", liftRightError);
	//writeDebugStreamLine("                     left curent %d", leftCurrent);
	//writeDebugStreamLine("                                    right curent %d", rightCurrent);
	//writeDebugStreamLine("                               Change in position %d", (leftPot - leftLastPot));
	//writeDebugStreamLine("  liftLeftAtPosition %d", liftLeftAtPosition);
	//writeDebugStreamLine("  curent %d", leftCurrent);
	//writeDebugStreamLine("  derivative %f", leftDerivative);
	//writeDebugStreamLine("  integral %f", sharedIntegral);
	//writeDebugStreamLine("  proportion %f", leftProportion);

	datalogAddValueWithTimeStamp(0, time1(T4));
	//datalogAddValueWithTimeStamp(1, leftLastPot);
	//datalogAddValueWithTimeStamp(2, liftkd);
	//datalogAddValueWithTimeStamp(3, leftCurrent);
}

void liftPIDCalculate (int position) {
	float leftCurrent;
	float rightCurrent;

	float integralAcitveZone = 100;

	float leftProportion;
	float sharedIntegral;
	float leftDerivative;
	float rightProportion;
	float rightDerivative;

	float liftLeftError;
	float liftRightError;
	float liftErrorT;
	float leftLastPot;
	float rightLastPot;

	float leftPot = SensorValue[liftLeftPot];
	float rightPot = SensorValue[liftRightPot];

	//Find lift error
	liftLeftError = position - leftPot;
	liftRightError = position - rightPot;

	leftProportion = liftLeftError * liftkp;
	rightProportion = liftRightError * liftkp;

	sharedIntegral = liftErrorT * liftki * 0.025;

	leftDerivative = ((leftPot - leftLastPot) * liftkd)/0.025;
	rightDerivative = ((rightPot - rightLastPot) * liftkd)/0.025;

	//Integral
	liftErrorT += liftLeftError;
	if (sharedIntegral > 80) {
		sharedIntegral = 80;
		} else if (sharedIntegral < -80) {
		sharedIntegral = -80;
	}

	leftCurrent = leftProportion + sharedIntegral + leftDerivative;
	rightCurrent = rightProportion + sharedIntegral + rightDerivative;

	/*if (abs(leftPot - leftLastPot) <= 1) {
	liftLeftAtPosition = true;
	} else {
	liftLeftAtPosition = false;
	}
	if (abs(leftPot - leftLastPot) <= 1) {
	liftRightAtPosition = true;
	} else {
	liftRightAtPosition = false;
	}*/

	if (leftCurrent > 127) {
		leftCurrent = 127;
	}
	if (rightCurrent > 127) {
		rightCurrent = 127;
	}
	if (leftCurrent < -127) {
		leftCurrent = -127;
	}
	if (rightCurrent < -127) {
		rightCurrent = -127;
	}

	motor[liftL] = leftCurrent;
	motor[liftR] = leftCurrent;

	//writeDebugStreamLine("left pot %d", leftPot);
	//writeDebugStreamLine("             right pot %d", rightPot);
	//writeDebugStreamLine("arm %d", armIsReallyBack);
	//writeDebugStreamLine("  left integral %d", sharedIntegral);
	//writeDebugStreamLine("                          right integral %d", rightIntegral);
	//writeDebugStreamLine("position %d", position);
	//writeDebugStreamLine("          left error %d", liftLeftError);
	//writeDebugStreamLine("                  right error %d", liftRightError);
	//writeDebugStreamLine("                     left curent %d", leftCurrent);
	//writeDebugStreamLine("                                    right curent %d", rightCurrent);
	//writeDebugStreamLine("                               Change in position %d", (leftPot - leftLastPot));
	//writeDebugStreamLine("  liftLeftAtPosition %d", liftLeftAtPosition);
	//writeDebugStreamLine("  curent %d", leftCurrent);
	//writeDebugStreamLine("  derivative %f", leftDerivative);
	//writeDebugStreamLine("  integral %f", sharedIntegral);
	//writeDebugStreamLine("  proportion %f", leftProportion);

	datalogAddValueWithTimeStamp(0, time1(T4));
	//datalogAddValueWithTimeStamp(1, leftLastPot);
	//datalogAddValueWithTimeStamp(2, liftkd);
	//datalogAddValueWithTimeStamp(3, leftCurrent);

	leftLastPot = leftPot;
	rightLastPot = rightPot;

	clearTimer(T4);
}

void liftPIDControl (int position) {
	if (time1[T4] > 25) {
		liftPIDCalculate(position);
	}
}

void checkLiftPos (int height) {
	if (SensorValue[liftLeftPot] >= height - 500) {
		liftLeftAtPosition = true;
		} else {
		liftLeftAtPosition = false;
	}
	if (SensorValue[liftRightPot] >= height - 500) {
		liftRightAtPosition = true;
		} else {
		liftRightAtPosition = false;
	}
}

void autoStackStep(int liftPos) {
	//Check if lift reaches height
	checkLiftPos(liftPos);

	if (outakeFinished) {
		stacking = false;
		stackPrev = false;
		justStacked = true;
		liftLeftAtPosition = false;
		liftRightAtPosition = false;
		armIsReallyBack = false;
		increaseStackLvl = true;
		writeDebugStreamLine("stage 4");
		} else {
		if (!armIsReallyBack) {
			liftPIDControl(liftPos);
			writeDebugStreamLine("stage 1");
			} else if (time1[T1] <= autoStackDownTime) {
			motor[liftL] = -60;
			motor[liftR] = -60;
			clearTimer(T3);
			} else if (time1[T1] >= autoStackDownTime) {
			rollerOutake(-127, autoStackOutTime);
			liftPIDControl(liftPos + autoStackExraHeight);
			writeDebugStreamLine("Second Pid and Outake");
		}

		if (liftLeftAtPosition /*&& liftRightAtPosition*/ && !armIsReallyBack) {
			moveArmIn();
			liftPIDControl(liftPos);
			//Not auto stacking stuff
			//armIsBack = false;
			writeDebugStreamLine("stage 2");
			clearTimer(T1);
		}
	}
}

void autoStack(int level) {
	switch (level) {
	case PRESET_LEVEL_ONE:
		autoStackStep(h1);
		break;

	case PRESET_LEVEL_TWO:
		autoStackStep(h2);
		break;

	case PRESET_LEVEL_THREE:
		autoStackStep(h3);
		break;

	case PRESET_LEVEL_FOUR:
		autoStackStep(h4);
		break;

	case PRESET_LEVEL_FIVE:
		autoStackStep(h5);
		break;

	case PRESET_LEVEL_SIX:
		autoStackStep(h6);
		break;

	case PRESET_LEVEL_SEVEN:
		autoStackStep(h7);
		break;

	case PRESET_LEVEL_EIGHT:
		autoStackStep(h8);
		break;

	case PRESET_LEVEL_NINE:
		autoStackStep(h9);
		break;

	case PRESET_LEVEL_TEN:
		autoStackStep(h10);
		break;

	case PRESET_LEVEL_ELEVEN:
		autoStackStep(h11);
		break;

	case PRESET_LEVEL_TWELVE:
		autoStackStep(h12);
		break;

	case PRESET_LEVEL_THIRTEEN:
		autoStackStep(h13);
		break;

	case PRESET_LEVEL_FOURTEEN:
		autoStackStep(h14);
		break;
	}
}

void postStacking() {
	moveArmOut();
	//armIsBack = true;
	if (!armIsReallyBack) {
		if (SensorValue[liftLeftPot] > 500 /*&& SensorValue[liftRightPot] > 500*/) {
			motor[liftL] = -127;
			motor[liftR] = -127;
			//liftPIDControl(350);
		}
		} else {
		motor[liftL] = -15;
		motor[liftR] = -15;
	}
	if (SensorValue[liftLeftPot] <= 370 /*&& SensorValue[liftRightPot] <= 370*/) {
		motor[liftL] = 0;
		motor[liftR] = 0;
		justStacked = false;
	}
	outakeFinished = false;
}

void autoDrivePIDCalculate (int distance, bool time) {
	float encAverage = (SensorValue[leftDriveEnc]+SensorValue[rightDriveEnc])/2;

	//float integralAcitveZone = 100;

	float error;
	float proportion;
	float integral;
	float derivative;

	float errorT;
	float lastError;

	float current;

	//Find Distance error
	error = distance - encAverage;

	//Set proportion
	proportion = error * drivekp;

	integral = errorT * driveki * 0.025;

	derivative = ((error - lastError) * drivekd)/0.025;


	//Calculate integral
	//left
	errorT += error;
	if (integral > 80) {
		integral = 80;
		} else if (integral < -80) {
		integral = -80;
	}

	//Set current
	current = proportion + integral + derivative;
	driveCurrent = proportion + integral + derivative;

	/*if (abs(error) <= drivePositionError) {
	current = 0;
	}

	if (abs(error) <= driveTurnPositionError) {
	gyroCurrent = 0;
	}*/

	//Check that drive has stopped
	if (abs(error - lastError) <= 2) {
		driveAtPosition = true;
		} else {
		driveAtPosition = false;
	}

	if (current > 127) {
		current = 127;
	}
	if (current < -127) {
		current = -127;
	}


	motor[driveBL] = current;
	motor[driveFL] = current;
	motor[driveBR] = current;
	motor[driveFR] = current;

	//writeDebugStreamLine("Current Angle %d", encAverage);
	//writeDebugStreamLine("            error %d", error);
	//writeDebugStreamLine("            last error %d", lastError);
	writeDebugStreamLine("        integral %d", integral);
	//writeDebugStreamLine("             error total %d", errorT);
	writeDebugStreamLine("                      derivative %d", derivative);
	//writeDebugStreamLine("           last error %d", lastError);
	//writeDebugStreamLine("             drive current 2/ %d", current);
	writeDebugStreamLine("proportion %d", proportion);
	//writeDebugStreamLine("             error %d", error);
	//writeDebugStreamLine("             distance %d", distance);

	//datalogAddValueWithTimeStamp(0, error);
	datalogAddValueWithTimeStamp(0, encAverage);
	/*datalogAddValueWithTimeStamp(2, integral);
	datalogAddValueWithTimeStamp(3, derivative);*/
	//datalogAddValueWithTimeStamp(3, lastError);
	datalogAddValueWithTimeStamp(2, current);
	datalogAddValueWithTimeStamp(1, distance);

	lastError = error;

	//Make sure the loop happens consistantly
	if (time) {
		clearTimer(T1);
	}
}

void autoDrivePIDControl (int distance, bool time) {
	if (time) {
		if (time1[T1] > 25) {
			autoDrivePIDCalculate(distance, time);
		}
		} else {
		autoDrivePIDCalculate(distance, time);
	}
}

void autoGyroPIDCalculate (int setAngle) {
	float angle = SensorValue(driveGyro);

	float integralAcitveZone = 1000;

	float proportion;
	float integral;
	float derivative;

	float errorT;
	float lastTurnError;

	float current;

	//Find Angle error
	turnError = setAngle - angle;

	//Set proportion
	proportion = turnError * turnkp;

	integral = errorT * turnki * 0.025;

	derivative = ((turnError - lastTurnError) * turnkd)/0.025;

	//Calculate integral
	errorT += turnError;
	if (integral > 80) {
		integral = 80;
		} else if (integral < -80) {
		integral = -80;
	}

	//Set current
	current = proportion + integral + derivative;

	/*if (abs(turnError) <= turnPositionError) {
	current = 0;
	}*/

	//Check that turn has stopped
	/*if (abs(turnError) <= turnPositionError) {
	turnAtPosition = true;
	} else {
	turnAtPosition = false;
	}*/

	if (current > 127) {
		current = 127;
	}
	if (current < -127) {
		current = -127;
	}

	//Send to motors
	motor[driveBL] = -current;
	motor[driveFL] = -current;
	motor[driveBR] = current;
	motor[driveFR] = current;

	//writeDebugStreamLine("Current Angle %d", currentAngle);
	//writeDebugStreamLine("            turn error %d", turnError);
	/*writeDebugStreamLine("             integral %d", integral);
	writeDebugStreamLine("             error total %d", errorT);
	writeDebugStreamLine("             derivative %d", derivative);
	writeDebugStreamLine("           last error %d", lastTurnError);*/
	//writeDebugStreamLine("             angle current 2/ %d", current);

	//datalogAddValueWithTimeStamp(4, turnError);
	datalogAddValueWithTimeStamp(0, angle);
	datalogAddValueWithTimeStamp(1, setAngle);
	datalogAddValueWithTimeStamp(2, current);
	/*datalogAddValueWithTimeStamp(2, integral);
	datalogAddValueWithTimeStamp(3, derivative);
	datalogAddValueWithTimeStamp(4, current);*/
	//datalogAddValueWithTimeStamp(4, turnError);

	lastTurnError = turnError;

	clearTimer(T1);
}

void autoGyroPIDControl (int setAngle) {
	if (time1[T1] > 25) {
		autoGyroPIDCalculate(setAngle);
	}
}

void autoDriveGyroPIDCalculate (int setAngle, int distance) {
	autoDrivePIDControl(distance, false);

	float angle = SensorValue(driveGyro);
	float gyroCurrent;

	//Find Angle error
	turnError = setAngle - angle;

	gyroCurrent = turnError * driveTurnkp;

	//Assign power to motors
	motor[driveBL] = driveCurrent - gyroCurrent;
	motor[driveFL] = driveCurrent - gyroCurrent;
	motor[driveBR] = driveCurrent + gyroCurrent;
	motor[driveFR] = driveCurrent + gyroCurrent;

	//Limit power to motors
	if (gyroCurrent > maxTurnPower) {
		gyroCurrent = maxTurnPower;
	}
	if (gyroCurrent < -maxTurnPower) {
		gyroCurrent = -maxTurnPower;
	}

	/*if (abs(turnError) <= turnDrivePositionError) {
	gyroCurrent = 0;
	}*/

	if (driveCurrent > 127 - maxTurnPower) {
		driveCurrent = (127 - maxTurnPower);
	}
	if (driveCurrent < -(127 - maxTurnPower)) {
		driveCurrent = -(127 - maxTurnPower);
	}

	/*writeDebugStreamLine("Angle current %d", gyroCurrent);
	writeDebugStreamLine("Drive current %d", driveCurrent);
	writeDebugStreamLine("             overall  current left %d", overallCurrentLeft);
	writeDebugStreamLine("             overall  current right %d", overallCurrentRight);*/
	//writeDebugStreamLine("             timer %d", SensorValue[driveGyro]);

	datalogAddValueWithTimeStamp(3, setAngle);
	datalogAddValueWithTimeStamp(4, angle);
	datalogAddValueWithTimeStamp(5, gyroCurrent);
	datalogAddValueWithTimeStamp(6, (driveCurrent + gyroCurrent));

	clearTimer(T1);
}

void autoDriveGyroPIDControl (int setAngle, int distance) {
	if (time1[T1] > 25) {
		autoDriveGyroPIDCalculate(setAngle, distance);
	}
}
void collectMobileGoal() {
	while (time1[T2] < 2500) {

		autoLiftPIDControl(600);

		//Move mobile goal lifter out
		if (!mobileGoalIsOut) {
			moveMobileGoalOut();
			} else {
			motor[mobileGoal] = -50;
		}

		if (autonomousConeNumber == CONE_LOADER) {
			if (time1[T2] > 900) {
				autoDriveGyroPIDControl(0, 1750);
			}
			} else {
			if (time1[T2] > 900) {
				autoDriveGyroPIDControl(0, 1900);
			}
		}
	}
}

void intakeMobileGoalAlignLoader() {
	while (time1[T2] < 2810) {

		//Move mobile goal lifter in
		if (mobileGoalIsOut) {
			moveMobileGoalIn();
			} else {
			motor[mobileGoal] = 40;
		}

		if (time1[T2] > 200 && time1[T2] < 1300) {
			autoDriveGyroPIDControl(0, -400);
			autoLiftPIDControl(600);
		}

		if (time1[T2] > 1300 && time1[T2] < 2300) {
			if (allianceSide == RIGHT) {
				autoGyroPIDControl(-900);
			}
			if (allianceSide == LEFT) {
				autoGyroPIDControl(900);
			}
			clearDriveEnc();
		}

		if (time1[T2] > 2300 && time1[T2] < 2800) {
			if (allianceSide == RIGHT) {
				autoDriveGyroPIDControl(-900, -340);
			}
			if (allianceSide == LEFT) {
				autoDriveGyroPIDControl(900, -340);
			}
			//autoLiftPIDControl(600);
			if (time1[T2] > 2600) {
				if (!mobileGoalIsOut) {
					motor[roller] = -100;
				}
			}
		}

		if (time1[T2] > 2800) {
			autoLiftPIDControl(600);
		}

		/*if (time1[T2] > 3000 && time1[T2] < 3200) {
		if (!mobileGoalIsOut) {
		motor[roller] = -100;
		}
		}*/
	}
}

void intakeMobileGoalAndStackFirstCone() {
	int timeReq = 3000;
	while (time1[T2] < timeReq) {

		if (time1[T2] < 1600) {
			autoDriveGyroPIDControl(0, 0);
			autoLiftPIDControl(600);
		}

		//Move mobile goal lifter out
		if (mobileGoalIsOut) {
			moveMobileGoalIn();
			} else {
			motor[mobileGoal] = 40;
		}

		if (time1[T2] > 1600 && time1[T2] < 2000) {
			if (!mobileGoalIsOut) {
				motor[roller] = -100;
			}
		}

		if (time1[T2] > 2000 && time1[T2] < 3000) {
			motor[roller] = 127;
			moveArmOut();
			autoLiftPIDControl(300);
		}

		if (time1[T2] > 2000) {
			autoDriveGyroPIDControl(0, 480);
		}

		if (autonomousConeNumber != CONE_NUMBER_2) {
			timeReq = 3500;
			if (time1[T2] > 3000) {
				moveArmIn();
			}

			if (time1[T2] > 3000) {
				motor[roller] = 40;
				autoLiftPIDControl(580);
			}
		}
	}
}

void stackSecondConeAndCollectThirdCone() {
	int timeReq = 1800;
	while (time1[T2] < timeReq) {

		if (time1[T2] > 150 && time1[T2] < 800) {
			motor[roller] = -100;
			autoLiftPIDControl(780);
		}

		if (time1[T2] > 800 && time1[T2] < 1800) {
			motor[roller] = 127;
			moveArmOut();
		}

		if (time1[T2] > 1060 && time1[T2] < 1800) {
			autoLiftPIDControl(280);
		}

		if (time1[T2] > 800) {
			autoDriveGyroPIDControl(0, 445);
		}

		if (autonomousConeNumber != CONE_NUMBER_3) {
			timeReq = 2500;
			if (time1[T2] > 1800) {
				moveArmIn();
				autoLiftPIDControl(690);
			}

			if (time1[T2] > 1800) {
				motor[roller] = 40;
				autoLiftPIDControl(690);
				moveArmIn();
			}
		}
	}
}

void stackThirdConeAndCollectFourthCone() {
	int timeReq = 2600;
	while (time1[T2] < timeReq) {

		if (time1[T2] < 600) {
			motor[roller] = -100;
			autoLiftPIDControl(840);
		}

		if (time1[T2] > 600 && time1[T2] < 2600) {
			motor[roller] = 127;
			moveArmOut();
		}

		if (time1[T2] > 850 && time1[T2] < 2600) {
			autoLiftPIDControl(280);
		}

		if (time1[T2] > 600) {
			autoDriveGyroPIDControl(0, 300);
		}

		if (autonomousConeNumber != CONE_NUMBER_4) {
			timeReq = 3900;
			if (time1[T2] > 2600) {
				moveArmIn();
				autoLiftPIDControl(840);
			}

			if (time1[T2] > 2800) {
				motor[roller] = 40;
				moveArmIn();
				autoLiftPIDControl(840);
			}
		}
	}
}


void autoAlignWithZones() {
	while (time1[T2] < 5000) {

		if (time1[T2] < 2300) {
			motor[roller] = 40;
			if (autonomousConeNumber == CONE_NUMBER_2) {
				if (time1[T2] < 300) {
					autoLiftPIDControl(580);
				}
				if (time1[T2] > 300) {
					autoLiftPIDControl(580);
					moveArmIn();
				}
				} else if (autonomousConeNumber == CONE_NUMBER_3) {
				if (time1[T2] < 600) {
					autoLiftPIDControl(740);
				}
				if (time1[T2] > 600 && time1[T2] < 1600) {
					autoLiftPIDControl(740);
					moveArmIn();
				}
				if (time1[T2] > 1600) {
					motor[liftL] = -15;
					motor[liftR] = -15;
				}
				} else if (autonomousConeNumber == CONE_NUMBER_4) {
				if (time1[T2] < 300) {
					autoLiftPIDControl(840);
				}
				if (time1[T2] > 300) {
					autoLiftPIDControl(840);
					moveArmIn();
				}
			}
			if (autonomousMode == AUTONOMOUS_MODE_MOBILE_GOAL_20 && autonomousConeNumber == CONE_NUMBER_4) {
				//autoDriveGyroPIDControl(0, -3200);
				autoDriveGyroPIDControl(0, -2700);
				} else if (autonomousMode == AUTONOMOUS_MODE_MOBILE_GOAL_20 && autonomousConeNumber == CONE_NUMBER_3) {
				autoDriveGyroPIDControl(0, -2400);
				} else if (autonomousMode == AUTONOMOUS_MODE_MOBILE_GOAL_10) {
				autoDriveGyroPIDControl(0, -2700);
				} else if (autonomousMode == AUTONOMOUS_MODE_MOBILE_GOAL_5) {
				autoDriveGyroPIDControl(0, -2600);
			}
		}

		if (allianceSide == RIGHT) {
			if (time1[T2] > 2300 && time1[T2] < 3000) {
				autoGyroPIDControl(-550);
				clearDriveEnc();
			}

			if (time1[T2] > 3000 && time1[T2] < 4100) {
				autoDriveGyroPIDControl(-550, -875);
			}

			if (time1[T2] > 4100) {
				autoGyroPIDControl(-1580);
			}
			} else if (allianceSide == LEFT) {
			if (time1[T2] > 2300 && time1[T2] < 3000) {
				autoGyroPIDControl(500);
				clearDriveEnc();
			}

			if (time1[T2] > 3000 && time1[T2] < 4100) {
				autoDriveGyroPIDControl(500, -875);
			}

			if (time1[T2] > 4100) {
				autoGyroPIDControl(1475);
			}
		}
	}
}

void scoreMobileGoalInZones() {
	while (time1[T2] < 2601) {

		if (time1[T2] > 620) {
			motor[roller] = -127;
			autoLiftPIDControl(900);
		}

		if (time1[T2] > 620) {
			if (!mobileGoalIsOut) {
				moveMobileGoalOut();
				} else {
				motor[mobileGoal] = -50;
			}
		}

		if (time1[T2] < 1700) {
			drive(127, 127);
			} else if (time1[T2] > 1700 && time1[T2] < 2300) {
			drive(-100, -100);
			} else {
			drive(0, 0);
		}
	}
}

void autoAutoStack(int level) {
	switch (level) {
	case PRESET_LEVEL_ONE:
		autoStackStep(ah1);
		break;

	case PRESET_LEVEL_TWO:
		autoStackStep(ah2);
		break;

	case PRESET_LEVEL_THREE:
		autoStackStep(ah3);
		break;

	case PRESET_LEVEL_FOUR:
		autoStackStep(ah4);
		break;

	case PRESET_LEVEL_FIVE:
		autoStackStep(ah5);
		break;

	case PRESET_LEVEL_SIX:
		autoStackStep(ah6);
		break;

	case PRESET_LEVEL_SEVEN:
		autoStackStep(ah7);
		break;

	case PRESET_LEVEL_EIGHT:
		autoStackStep(ah8);
		break;

	case PRESET_LEVEL_NINE:
		autoStackStep(ah9);
		break;

	case PRESET_LEVEL_TEN:
		autoStackStep(h10);
		break;

	case PRESET_LEVEL_ELEVEN:
		autoStackStep(h11);
		break;

	case PRESET_LEVEL_TWELVE:
		autoStackStep(h12);
		break;

	case PRESET_LEVEL_THIRTEEN:
		autoStackStep(h13);
		break;

	case PRESET_LEVEL_FOURTEEN:
		autoStackStep(h14);
		break;
	}
}

void autoPostStacking() {
	moveArmOut();
	//armIsBack = true;
	if (!armIsReallyBack) {
		if (SensorValue[liftLeftPot] > 800 /*&& SensorValue[liftRightPot] > 500*/) {
			clearTimer(T1);
			motor[liftL] = -127;
			motor[liftR] = -127;
			//liftPIDControl(350);
		}
	}
	if (SensorValue[liftLeftPot] <= 800 /*&& SensorValue[liftRightPot] <= 370*/) {
		if (time1[T1] < 800) {
			motor[roller] = 127;
			motor[liftL] = -15;
			motor[liftR] = -15;
			writeDebugStreamLine("working");
		}
		if (time1[T1] > 800) {
			motor[liftL] = 0;
			motor[liftR] = 0;
			increaseAutoStackLvl = true;
			stacking = true;
			justStacked = false;
			increaseAutoStackLvl = false;
			armIsReallyBack = false;
			writeDebugStreamLine("working  2");
		}
	}
	outakeFinished = false;
}

void autoAutoStackControl (int maxConeNum) {
	if (stacking) {
		autoAutoStack(autoStacklvl);
	}
	if (justStacked) {
		autoPostStacking();
	}

	if (increaseAutoStackLvl) {
		autoStacklvl ++;
	}
}

void autoLoader () {
	int timeReq = 5800;
	while (time1[T2] < timeReq) {
		//Passive Drive Power For Stacking
		drive(5, 5);

		//Cone #2
		if (time1[T2] < 500) {
			moveArmOut();
			motor[roller] = 127;
			liftPIDControl(850);
		}
		if (time1[T2] > 500 && time1[T2] < 1200) {
			moveArmIn();
			liftPIDControl(600);
			motor[roller] = 40;
		}
		if (time1[T2] > 1200 && time1[T2] < 1400) {
			motor[roller] = -127;
			liftPIDControl(600);
		}

		//Cone #3
		if (time1[T2] > 1400 && time1[T2] < 1900) {
			moveArmOut();
			motor[roller] = 127;
			liftPIDControl(850);
		}
		if (time1[T2] > 1900 && time1[T2] < 2500) {
			moveArmIn();
			liftPIDControl(675);
			motor[roller] = 40;
		}
		if (time1[T2] > 2500 && time1[T2] < 2700) {
			motor[roller] = -127;
			liftPIDControl(675);
		}

		//Cone #4
		if (time1[T2] > 2700 && time1[T2] < 3200) {
			/*stacking = true;
			justStacked = false;
			increaseAutoStackLvl = false;
			armIsReallyBack = false;*/
			moveArmOut();
			motor[roller] = 127;
			liftPIDControl(850);
		}
		if (time1[T2] > 3200 && time1[T2] < 3800) {
			moveArmIn();
			liftPIDControl(800);
			motor[roller] = 40;
		}
		if (time1[T2] > 3800 && time1[T2] < 4000) {
			motor[roller] = -127;
			liftPIDControl(800);
		}

		//Cone #5
		if (time1[T2] > 4000 && time1[T2] < 4500) {
			moveArmOut();
			motor[roller] = 127;
			liftPIDControl(850);
		}
		if (time1[T2] > 4500 && time1[T2] < 5100) {
			moveArmIn();
			liftPIDControl(900);
			motor[roller] = 40;
		}
		if (time1[T2] > 5100 && time1[T2] < 5300) {
			motor[roller] = -127;
			liftPIDControl(1100);
		}

		//Cone #6
		if (time1[T2] > 5300 && time1[T2] < 5800) {
			moveArmOut();
			motor[roller] = 127;
			liftPIDControl(850);
		}

		if (autonomousMode == AUTONOMOUS_MODE_MOBILE_GOAL_5) {
			timeReq = 7200;
			if (time1[T2] > 5800 && time1[T2] < 6500) {
				moveArmIn();
				liftPIDControl(1150);
				motor[roller] = 40;
			}
			if (time1[T2] > 6500 && time1[T2] < 6700) {
				motor[roller] = -127;
				liftPIDControl(1200);
			}

			//Cone #7
			if (time1[T2] > 6700 && time1[T2] < 7200) {
				moveArmOut();
				motor[roller] = 127;
				liftPIDControl(850);
			}
		}
		/*if (time1[T2] > 7200 && time1[T2] < 7900) {
		moveArmIn();
		liftPIDControl(1250);
		motor[roller] = 40;
		}
		if (time1[T2] > 7900 && time1[T2] < 8100) {
		motor[roller] = -127;
		liftPIDControl(1250);
		}*/

		//Stack other cones
		/*if (time1[T2] > 4100) {
		autoAutoStackControl(6);
		}*/
		//autoAutoStackControl(6);
	}
}

void scoreConeOnStationaryGoal() {
	while (time1[T2] < 3000) {
		if (time1[T2] < 1300) {
			autoLiftPIDControl(1200);
			autoDriveGyroPIDControl(0, 525);
		}

		if (time1[T2] > 1300 && time1[T2] < 1800) {
			moveArmOut();
			autoLiftPIDControl(1200);
		}

		if (time1[T2] > 1800) {
			motor[roller] = -120;
			moveArmIn();
		}

		if (time1[T2] > 2300) {
			autoDriveGyroPIDControl(0, 100);
		}

	}
}

void stationaryBlock() {
	while (time1[T2] < 3000) {
		if (time1[T2] < 1000) {
			if (allianceSide == RIGHT) {
				motor[liftL] = -80;
				motor[liftR] = -80;
				autoGyroPIDControl(-800);
				clearDriveEnc();
				} else if (allianceSide == LEFT) {
				motor[liftL] = -80;
				motor[liftR] = -80;
				autoGyroPIDControl(600);
				clearDriveEnc();
			}
		}

		if (time1[T2] > 1000) {
			if (allianceSide == RIGHT) {
				autoDriveGyroPIDControl(-800, 3000);
				} else if (allianceSide == LEFT) {
				autoDriveGyroPIDControl(600, 3000);
			}
		}
	}
}

void skillsFirstMobileGoal() {
	while (time1[T2] < 14500) {
		if (time1[T2] < 7400) {
			motor[roller] = 40;
		}
		if (time1[T2] < 2000) {
			//Move mobile goal lifter out
			if (!mobileGoalIsOut) {
				moveMobileGoalOut();
			} else {
				motor[mobileGoal] = -50;
			}
		}

		if (time1[T2] < 2000) {
			autoLiftPIDControl(600);
		}

		if (time1[T2] > 800 && time1[T2] < 3500) {
			autoDriveGyroPIDControl(0, 1000);
		}

		if (time1[T2] > 3500 && time1[T2] < 12000) {
			//Move mobile goal lifter in
			if (mobileGoalIsOut) {
				moveMobileGoalIn();
				} else {
				motor[mobileGoal] = 40;
			}
		}


		if (time1[T2] > 4500 && time1[T2] < 7000) {
			autoGyroPIDControl(1800);
			clearDriveEnc();
		}

		if (time1[T2] > 7500 && time1[T2] < 8800) {
			autoDriveGyroPIDControl(1800, 970);
		}

		if (time1[T2] > 8800 && time1[T2] < 9200) {
			motor[roller] = -127;
		}

		if (time1[T2] > 9000 && time1[T2] < 10000) {
			autoGyroPIDControl(1000);
			clearDriveEnc();
		}

		if (time1[T2] > 10000 && time1[T2] < 11000) {
			autoDriveGyroPIDControl(1000, 370);
		}

		if (time1[T2] > 11000 && time1[T2] < 12000) {
			autoGyroPIDControl(1900);
			clearDriveEnc();
		}

		if (time1[T2] > 12300) {
			autoLiftPIDControl(700);
			motor[roller] = -100;
			//Move mobile goal lifter out
			if (!mobileGoalIsOut) {
				moveMobileGoalOut();
			} else {
				motor[mobileGoal] = -50;
			}
		}

		if (time1[T2] > 12000) {
			autoDriveGyroPIDControl(1900, 800);
		}
	}
}

void skillsSecondMobileGoal() {
	while (time1[T2] < 14000) {

		if (time1[T2] < 1000) {
			autoDriveGyroPIDControl(1900, -800);
		}

		if (time1[T2] > 1000 && time1[T2] < 2500) {
			autoGyroPIDControl(1000);
			clearDriveEnc();
			//Move mobile goal lifter in
			if (mobileGoalIsOut) {
				moveMobileGoalIn();
				} else {
				motor[mobileGoal] = 40;
			}
		}

		if (time1[T2] > 2500 && time1[T2] < 3500) {
			autoDriveGyroPIDControl(1000, 600);
			//Move mobile goal lifter in
			if (mobileGoalIsOut) {
				moveMobileGoalIn();
				} else {
				motor[mobileGoal] = 40;
			}
		}

		if (time1[T2] > 3500 && time1[T2] < 6000) {
			autoGyroPIDControl(0);
			clearDriveEnc();
			//Move mobile goal lifter out
			if (!mobileGoalIsOut) {
				moveMobileGoalOut();
			} else {
				motor[mobileGoal] = -50;
			}
		}

		if (time1[T2] > 6000 && time1[T2] < 9000) {
			autoDriveGyroPIDControl(0, 720);
		}

		if (time1[T2] > 7000 && time1[T2] < 9000) {
			//Move mobile goal lifter in
			if (mobileGoalIsOut) {
				moveMobileGoalIn();
				} else {
				motor[mobileGoal] = 40;
			}
		}

		if (time1[T2] > 9000 && time1[T2] < 11000) {
			autoGyroPIDControl(2000);
			clearDriveEnc();
		}

		if (time1[T2] > 11000 && time1[T2] < 13500) {
			autoDriveGyroPIDControl(2000, 1000);

			//Move mobile goal lifter out
			if (!mobileGoalIsOut) {
				moveMobileGoalOut();
			} else {
				motor[mobileGoal] = -50;
			}
		}
	}
}

void skillsThirdMobileGoal() {
	while (time1[T2] < 190000) {
			if (time1[T2] < 3000) {
				autoDriveGyroPIDControl(1900, -1000);
			}

			if (time1[T2] > 1000 && time1[T2] < 5000) {
				//Move mobile goal lifter in
				if (mobileGoalIsOut) {
					moveMobileGoalIn();
				} else {
					motor[mobileGoal] = 40;
				}
			}

			if (time1[T2] > 3000 && time1[T2] < 5000) {
				autoGyroPIDControl(-10);
				clearDriveEnc();
			}


			if (time1[T2] > 5000 && time1[T2] < 7000) {
				autoDriveGyroPIDControl(-10, 1000);
			}

			if (time1[T2] > 7010 && time1[T2] < 9000) {
				autoDriveGyroPIDControl(-10, 400);
			}

			if (time1[T2] > 7000 && time1[T2] < 9000) {
				//Move mobile goal lifter out
				if (!mobileGoalIsOut) {
					moveMobileGoalOut();
				} else {
					motor[mobileGoal] = -50;
				}
			}

			if (time1[T2] > 9000 && time1[T2] < 9010) {
				clearDriveEnc();
			}

			if (time1[T2] > 9010 && time1[T2] < 11000) {
				autoDriveGyroPIDControl(-10, 600);
			}

			if (time1[T2] > 10000 && time1[T2] < 14000) {
				//Move mobile goal lifter in
				if (mobileGoalIsOut) {
					moveMobileGoalIn();
				} else {
					motor[mobileGoal] = 40;
				}
			}

			if (time1[T2] > 11000 && time1[T2] < 11010) {
				clearDriveEnc();
			}

			if (time1[T2] > 11010 && time1[T2] < 12000) {
				autoDriveGyroPIDControl(-10, 1400);
			}

			if (time1[T2] > 12000 && time1[T2] < 13000) {
				autoGyroPIDControl(-700);
				clearDriveEnc();
			}

			if (time1[T2] > 13000 && time1[T2] < 14000) {
				autoDriveGyroPIDControl(-700, 600);
			}

			if (time1[T2] > 14000 && time1[T2] < 15000) {
				autoGyroPIDControl(-20);
				clearDriveEnc();
			}

			if (time1[T2] > 15000 && time1[T2] < 18000) {
				autoDriveGyroPIDControl(-20, 900);
			}

			if (time1[T2] > 15000) {
				//Move mobile goal lifter out
				if (!mobileGoalIsOut) {
					moveMobileGoalOut();
				} else {
					motor[mobileGoal] = -50;
				}
			}

			if (time1[T2] > 18000) {
				autoDriveGyroPIDControl(-20, -100);
			}
	}
}


void loaderPlacement() {
	int timeReq = 4400;
	while (time1[T2] < timeReq) {

		if (time1[T2] < 900) {
			if (allianceSide == RIGHT) {
				if (autonomousMode == AUTONOMOUS_MODE_MOBILE_GOAL_5) {
					autoGyroPIDControl(-1600);
				}
				if (autonomousMode == AUTONOMOUS_MODE_MOBILE_GOAL_10) {
					autoGyroPIDControl(-1800);
				}
			}
			if (allianceSide == LEFT) {
				if (autonomousMode == AUTONOMOUS_MODE_MOBILE_GOAL_5) {
					autoGyroPIDControl(1600);
				}
				if (autonomousMode == AUTONOMOUS_MODE_MOBILE_GOAL_10) {
					autoGyroPIDControl(1700);
				}
			}
			clearDriveEnc();
		}

		if (autonomousMode == AUTONOMOUS_MODE_MOBILE_GOAL_5) {
			if (time1[T2] < 450) {
				moveArmIn();
				motor[liftL] = 127;
				motor[liftR] = 127;
				motor[roller] = 40;
			}
			if (time1[T2] > 450) {
				motor[liftL] = 0;
				motor[liftR] = 0;
			}
			if (time1[T2] > 800 && time1[T2] < 1900) {
				motor[roller] = -127;
				//autoLiftPIDControl(1250);
			}
		}

		if (autonomousMode == AUTONOMOUS_MODE_MOBILE_GOAL_10) {
			if (time1[T2] > 200 && time1[T2] < 550) {
				moveArmIn();
				motor[liftL] = 127;
				motor[liftR] = 127;
				motor[roller] = 40;
			}
			if (time1[T2] > 550) {
				motor[liftL] = 0;
				motor[liftR] = 0;
			}
			if (time1[T2] > 1000 && time1[T2] < 1900) {
				motor[roller] = -127;
				//autoLiftPIDControl(1250);
			}
		}

		if (autonomousMode == AUTONOMOUS_MODE_MOBILE_GOAL_5) {
			if (time1[T2] > 800 && time1[T2] < 1800) {
				if (!mobileGoalIsOut) {
					moveMobileGoalOut();
					} else {
					motor[mobileGoal] = -50;
				}
			}

			if (time1[T2] > 900 && time1[T2] < 1400 ) {
				if (allianceSide == RIGHT) {
					autoDriveGyroPIDControl(-1600, 250);
				}
				if (allianceSide == LEFT) {
					autoDriveGyroPIDControl(1600, 250);
				}
			}

			if (time1[T2] > 2400 && time1[T2] < 4400) {
				if (allianceSide == RIGHT) {
					autoDriveGyroPIDControl(-1600, -300);
				}
				if (allianceSide == LEFT) {
					autoDriveGyroPIDControl(1600, -300);
				}
			}
		}

		if (autonomousMode == AUTONOMOUS_MODE_MOBILE_GOAL_10) {
			timeReq = 3700;
			if (time1[T2] > 1000 && time1[T2] < 2100) {
				if (!mobileGoalIsOut) {
					moveMobileGoalOut();
					} else {
					motor[mobileGoal] = -50;
				}
			}

			if (time1[T2] > 900 && time1[T2] < 2100 ) {
				if (allianceSide == RIGHT) {
					autoDriveGyroPIDControl(-1800, 1200);
				}
				if (allianceSide == LEFT) {
					autoDriveGyroPIDControl(1700, 1200);
				}
			}

			if (time1[T2] > 2100 && time1[T2] < 2700 ) {
				if (allianceSide == RIGHT) {
					drive(25, 127);
					clearDriveEnc();
				}
				if (allianceSide == LEFT) {
					drive(127, 25);
					clearDriveEnc();
				}
			}

			if (time1[T2] > 2700 && time1[T2] < 3700) {
				if (allianceSide == RIGHT) {
					drive(-127, -127);
				}
				if (allianceSide == LEFT) {
					drive(-127, -127);
				}
			}
		}
	}
}
